### ISSUE TITLE
Events Enhancements

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#50]
Use the new event system to update the deployments in the ui when:
- [x] A deployment is created
- [x] A deployment is updated

**Comment by MarcDAFrame** [comment]
admin
- [ ] create user
- [ ] edit user
- [ ] verify
- [ ] disable

I'm not doing these right now because there is a better way to handle events, still deciding what the right way is to, but I think implementing it within `app/models/Base/index.ts` with an events variable that looks like the following
```typescript
this.events = {
  success: {event: eventTypes.DEPLOYMENT_CRUD, message: 'create'}
  error: {event: eventTypes.DEPLOYMENT_ERR, message: 'error'}
}
```

would be the most organized way

**Comment by saidghamra** [comment]
In `develop`
