### ISSUE TITLE
Display Error Messages When an Account Is Disabled or Not Verified

### ISSUE THREAD

**Issue by MarcDAFrame** [AgoraCloud/ui#51]

**Comment by saidghamra** [comment]
We did some testing today and it turns out that the UI already handles the user is not verified and user is not disabled use cases:

![image](https://user-images.githubusercontent.com/35788699/134264413-358deeb6-b4f5-4ca8-bee7-5b5f443edc21.png)

![image](https://user-images.githubusercontent.com/35788699/134264426-a2e6619f-160e-4c22-a0e8-d2f35a6f22d0.png)
