### ISSUE TITLE
Implement Sign Up Page

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#8]
We need to:
- [x] Implement basic form functionality to sign up
- [x] Show a pop up or something with error message on POST 3xx, 4xx and 5xx status codes
- [x] snackbar for api errors bottom centre
- [x] Show validation errors for inputs
- [x] Disable sign up button with invalid input

**Comment by waleedza99** [comment]
### 2021-01-29
### What I have done
- Read the documentation and watched videos about things (material-ui, mobx, etc) I didn't understand in the startup code I received from marc.
- Implemented the signup functionality (i.e. when the user clicks on signup button they receive an email for verification given that this email is not already associated with an account in the db, etc)
- Played with material-ui snackbars to display the messages from the server (i.e. was the request to registerer this user successful, or did the request fail and the server returned an error) to the user on the signup screen.

### What needs to be done

- Marc asked me to make the snackbar as a store that can be used by any other component that requires it (i.e. the snackbar component shouldn't be specific to signup page only)
- I need to find out about all the possible status codes I can get back from the server and what they mean so I can display the user a message from the server accordingly

**Comment by MarcDAFrame** [comment]
finished the login and signup pages

**Comment by waleedza99** [comment]
Sign up page would refresh every time the user clicked the "Signup" button so to fix this issue I removed the "this.loadUser()" function call because it was unnecessarily carried over from the login page section of the code into sign up page section of the code. "this.loginForm.message" was being used on line 81 of AuthStore.ts so the if there were error messages from the server they wouldn't be rendered on the signup page, to fix this issue I replaced this code with "this.signupForm.message"
