### ISSUE TITLE
End to End Testing - Part 3 - Write Project Test Suites

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#83]
# Overview
In part 3 of writing the end to end test suites, Waleed will write test suites to make sure that projects, project lanes and project tasks have E2E test coverage and function as expected.

For example, Waleed will make sure that if the user creates a new project in the UI, the user can see the three lanes: `To Do`, `Doing` and `Done`.

# To Do
- [x] Projects
- [x] Project Lanes
- [x] Project Tasks

**Comment by waleedza99** [comment]
The work on this issue is complete for now, however, it must be noted that the delete functionality could not be tested for projects, lanes and tasks simply because it is broken right now... Once delete functionality works for all components then more tests will be added to test the delete functionality of projects, lanes and tasks.
